### ISSUE TITLE
Rounding option for string ctor

### ISSUE THREAD

**Issue by schveiguy** [m3m0ry/fixedpoint#6]
I'm parsing values from a money column and I want to round to the nearest cent. However, Fixed is going to truncate instead. It would be nice to include a rounding option on the ctor.

**Comment by schveiguy** [comment]
Thanks, I'm going to submit a PR to fix the allocation.

**Comment by m3m0ry** [comment]
:facepalm: I completely forgot about negative numbers.
Yeah the allocation was also stupid on my part, I stopped thinking about it literally one step before I would arrive at the same solution.

I will have time in November to do some tinkering if necessary.
Thank you for your PR :heart:

**Comment by schveiguy** [comment]
Yeah, I just submitted the issue fully intending to do it myself. But was in the middle of a project and couldn't at the time do it myself.

Thanks!
